### ISSUE TITLE
Error in changing net bottleneck and input size

### ISSUE THREAD

**Issue by rschneider1998** [prajwalsingh/TreeGCN-ED#1]
Hey there,
i came across the problem, that the variables N (pointcloud size) and latent_dim (bottleneck of the net) are impletet, but not used in the TreeED architecture. That´s why i got errors concerning dimension of tensors.

By making the following changes in tree_model -> TreeED __init__, i got it in work (test pending):
`filters_enc         = [3, 32, 64, 128, 128, 256, 512]` to
`filters_enc         = [3, 32, 64, 128, 128, 256, latent_dim]`

and 

`downsample_enc      = [2,  2,  2,   2,   2,  64]` to
`downsample_enc      = [2,  2,  2,   2,   2,  (N*64)//2048]` &&
`degrees_dec         = [         1,   2,   2,   2,   2,   2,  64` to
`degrees_dec         = [         1,   2,   2,   2,   2,   2,  (N*64)//2048]`

Maybe that´s useful for someone else.

**Comment by prajwalsingh** [comment]
Thanks, I have made the suggested changes in the code, for latent_dim I forgot to change it back from hardcode to variable mode.

**Comment by rschneider1998** [comment]
That was a fast one! Thank you for the fast reply and commit. Btw: your code is a big help at my current master´s thesis.
